# This file is part of Wendy.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[dev.test]
image = "busybox:musl"

  [dev.test.vars]
  env = "test"
  url = "test.com"

  [[dev.test.resources]]
  name = "my-source"
  type = "external"
  provider = "git"

    [dev.test.resources.params]
    branch = "master"
    repo = "https://github.com/bob-cd/bob.git"

  [[dev.test.resources]]
  name = "another-source"
  type = "external"
  provider = "git"

    [dev.test.resources.params]
    branch = "master"
    repo = "https://github.com/lispyclouds/clj-docker-client.git"

  [[dev.test.steps]]
  cmd = "echo hello"

  [[dev.test.steps]]
  cmd = "sleep 10"

  [[dev.test.steps]]
  cmd = "sh -c 'touch test.txt && echo $env >> test.txt'"
  produces_artifact = { name = "afile", path = "test.txt", store = "local" }

  [[dev.test.steps]]
  cmd = "cat test.txt"

  [[dev.test.steps]]
  needs_resource = "my-source"
  cmd = "ls"
  produces_artifact = { name = "afile1", path = "LICENSE", store = "local" }
