# This file is part of Wendy.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[dev.test]
image = "clojure:latest"

  [[dev.test.resources]]
  name = "my-source"
  type = "external"
  provider = "git"

    [dev.test.resources.params]
    branch = "master"
    url = "https://github.com/bob-cd/bob.git"

  [[dev.test.steps]]

  [[dev.test.steps.in_parallel]]
  needs_resource = "my-source-code"
  cmd = "lein test :unit"

  [[dev.test.steps.in_parallel]]
  needs_resource = "my-source-code"
  cmd = "lein test :integration"

[dev.build-and-push]
image = "clojure:latest"

  [[dev.build-and-push.env]]
  password = "test"
  user = "test"

  [[dev.build-and-push.resources]]
  name = "my-source"
  type = "external"
  provider = "git"

    [dev.build-and-push.resources.params]
    branch = "master"
    url = "https://github.com/bob-cd/bob.git"

  [[dev.build-and-push.steps]]

  [[dev.build-and-push.steps.in_parallel]]
  needs_resource = "my-source-code"
  produces_artifact = { name = "jar", path = "target/bob-standalone.jar" }
  cmd = "lein uberjar"

  [[dev.build-and-push.steps.in_parallel]]
  needs_resource = "my-source-code"
  cmd = "lein deploy clojars"

[dev.package]
image = "debian:latest"

  [[dev.package.resources]]
  name = "my-jar"
  type = "artifact"
  provider = "dev.build-and-push"

  [[dev.package.steps]]
  needs_resource = "my-jar"
  produces_artifact = { name = "dev-installer", path = "bob.deb" }
  cmd = "make deb-package"

[stable.sign]
image = "debian:latest"

  [[stable.sign.resources]]
  name = "my-jar"
  type = "artifact"
  provider = "dev.build-and-push"

  [[stable.sign.steps]]
  needs_resource = "my-jar"
  produces_artifact = { name = "my-sign", path = "bob.sig" }
  cmd = "gpg --output bob.sig --sign bob-standalone.jar"

[stable.deploy]
image = "ansible:latest"

  [[stable.deploy.resources]]
  name = "my-jar"
  type = "artifact"
  provider = "dev.build-and-push"

  [[stable.deploy.resources]]
  name = "my-sign"
  type = "artifact"
  provider = "stable.sign"

  [[stable.deploy.steps]]

  [[stable.deploy.steps.in_parallel]]
  needs_resource = "my-sign"
  cmd = "scp user@cdn.com *.sig"

  [[stable.deploy.steps.in_parallel]]
  needs_resource = "my-jar"
  cmd = "scp user@cdn.com *.jar"

  [[stable.deploy.steps]]
  cmd = "ansible deploy prod"
